# Lab 1: Introduction to OpenCV

The goal of this first lab is to present a small introduction to image processing using OpenCV. In each section, you can find:
* a small example - analyse the code and try it
* some exercises

In [ ]:
# Requirements for this tutorial
! pip install opencv-python
! pip install numpy

In [ ]:
# If you prefer, you can convert this notebook to a Python script by uncommenting the following command
! pip install nbconvert
! jupyter nbconvert --to script 01-introduction.ipynb

In [1]:
import cv2
import numpy as np
import os

dataDir = './data'

### 1. Images – read, write and display; ROIs

In [2]:
# Opening an image
img = cv2.imread(os.path.join(dataDir, 'ml.jpg'))

# Showing the image
cv2.imshow("ml.jpg", img)

# Waiting for user to press a key to close the image
cv2.waitKey(0)

# Close the window after user pressed a key
cv2.destroyWindow("ml.jpg")

NameError: name 'cv2' is not defined

In [4]:
# Check image size
h, w, c = img.shape
print(f'height: {h}')
print(f'width: {w}')
print(f'channels: {c}')

height: 380
width: 308
channels: 3


In [5]:
# Saving image in bmp format
cv2.imwrite('ml_new.bmp', img)

True

Exercise 1.1 - Read any other color image from a file, show the mouse cursor over the image, and the coordinates and RGB components of the pixel under the cursor. When the user clicks on the mouse, let him modify the RGB components of the selected pixel.

In [9]:
img = cv2.imread(os.path.join(dataDir, 'ml.jpg'))

def paint_coordinates(event, x, y, flag, params):
    if event == cv2.EVENT_MOUSEMOVE:
        print(f'Coordinates: ({x}, {y})')
        print(f'RBG: {img[y][x]}')
    elif event == cv2.EVENT_LBUTTONDOWN:
        img[y][x] = [255, 0, 0]

cv2.namedWindow('image_window')
cv2.setMouseCallback('image_window', paint_coordinates)

while True:
    cv2.imshow("image_window", img)
    if cv2.waitKey(1) == ord('q'):
        break


cv2.destroyWindow("image_window")

Coordinates: (306, 253)
RBG: [255 255 255]
Coordinates: (298, 249)
RBG: [255 255 255]
Coordinates: (292, 245)
RBG: [255 255 255]
Coordinates: (285, 241)
RBG: [248 253 255]
Coordinates: (279, 239)
RBG: [197 216 223]
Coordinates: (276, 236)
RBG: [205 226 234]
Coordinates: (270, 233)
RBG: [214 233 241]
Coordinates: (267, 230)
RBG: [215 234 242]
Coordinates: (261, 229)
RBG: [210 233 241]
Coordinates: (256, 225)
RBG: [185 213 220]
Coordinates: (251, 222)
RBG: [164 189 193]
Coordinates: (246, 217)
RBG: [250 255 255]
Coordinates: (242, 212)
RBG: [173 174 172]
Coordinates: (234, 206)
RBG: [255 255 255]
Coordinates: (230, 198)
RBG: [255 255 255]
Coordinates: (224, 191)
RBG: [246 253 246]
Coordinates: (220, 185)
RBG: [254 255 248]
Coordinates: (216, 179)
RBG: [251 250 246]
Coordinates: (214, 177)
RBG: [255 255 246]
Coordinates: (212, 174)
RBG: [254 255 251]
Coordinates: (210, 172)
RBG: [255 254 254]
Coordinates: (210, 170)
RBG: [255 254 253]
Coordinates: (209, 169)
RBG: [255 255 249]
Coordinates

error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window_w32.cpp:1261: error: (-27:Null pointer) NULL window: 'image_window' in function 'cvDestroyWindow'


Exercise 1.2 - Allow the user to select a region of interest (ROI) in the image, by clicking on two points that identify two opposite corners of the selected ROI, and save the ROI into another file.

In [3]:
img = cv2.imread(os.path.join(dataDir, 'ml.jpg'))


r = cv2.selectROI(img)

cv2.destroyAllWindows()

x = int(r[0])
y = int(r[1])
width = int(r[2])
height = int(r[3])

cropped_image = img[y:y+height, x:x+width]


cv2.imwrite('crop.bmp', cropped_image)


True

### 2. Images – representation, grayscale and color, color spaces

In [3]:
# Create a white image
m = np.ones((100,200,1), np.uint8)

# Change the intensity to 100
m = m * 100

# Display the image
cv2.imshow('Grayscale image', m)
cv2.waitKey(0)
cv2.destroyWindow('Grayscale image')

In [5]:
# Draw a line with thickness of 5 px
cv2.line(m, (0,0), (200,100), 255, 5)
cv2.line(m, (200, 0), (0, 100), 255, 5)
cv2.imshow('Grayscale image with diagonals', m)
cv2.waitKey(0)
cv2.destroyWindow('Grayscale image with diagonals')

Exercise 2.1 - Create a color image with 100(lines)x200(columns) pixels with yellow color; draw the two diagonals of the image, one in red color, the other in blue color. Display the image.

In [10]:
# Create a white image
m = np.zeros((100,200,3), np.uint8)

m[:,:,1:] = 255

cv2.line(m, (0,0), (200,100), [0, 0, 255], 5)
cv2.line(m, (200, 0), (0, 100), [255, 0, 0], 5)
# Display the image
cv2.imshow('Yellow image', m)
cv2.waitKey(0)
cv2.destroyWindow('Yellow image')

Exercise 2.2 - Read any color image, in RGB format, display it in one window, convert it to grayscale, display the grayscale image in another window and save the grayscale image to a different file

In [11]:
img = cv2.imread(os.path.join(dataDir, 'ml.jpg'))

cv2.imshow('normal', img)

img_grayscale = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

cv2.imshow('grayscale', img_grayscale)
cv2.waitKey(0)
cv2.destroyAllWindows()

Exercise 2.3 - Split the 3 RGB channels and show each channel in a separate window. Add a constant value to one of the channels, merge the channels into a new color image and show the resulting image.

In [9]:
img = cv2.imread(os.path.join(dataDir, 'ml.jpg'))

cv2.imshow('normal', img)

img_blue = np.zeros(img.shape, np.uint8)
img_blue[:,:,0] = img[:,:,0]

img_green = np.zeros(img.shape, np.uint8)
img_green[:,:,1] = img[:,:,1]

img_red = np.zeros(img.shape, np.uint8)
img_red[:,:,2] = img[:,:,2]

cv2.imshow('blue', img_blue)

cv2.imshow('green', img_green)

cv2.imshow('red', img_red)
cv2.waitKey(0)
cv2.destroyAllWindows()

Exercise 2.4 - Convert the image to HSV, split the 3 HSV channels and show each channel in a separate window. Add a constant value to saturation channel, merge the channels into a new color image and show the resulting image.

In [2]:
img = cv2.imread(os.path.join(dataDir, 'ml.jpg'))

cv2.imshow('normal', img)

img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

print(img_hsv)
img_hsv[:, :, 1] += 50
img_hsv[:, :, 2] -= 50
print(img_hsv)

img_saturated = cv2.cvtColor(img_hsv, cv2.COLOR_HSV2BGR)

cv2.imshow('HSV', img_saturated)

cv2.waitKey(0)
cv2.destroyAllWindows()


[[[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 ...

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]]
[[[  0  50 205]
  [  0  50 205]
  [  0  50 205]
  ...
  [  0  50 205]
  [  0  50 205]
  [  0  50 205]]

 [[  0  50 205]
  [  0  50 205]
  [  0  50 205]
  ...
  [  0  50 205]
  [  0  50 205]
  [  0  50 205]]

 [[  0  50 205]
  [  0  50 205]
  [  0  50 205]
  ...
  [  0  50 205]
  [  0  50 205]
  [  0  50 205]]

 ...

 [[  0  50 205]
  [  0  50 205]
  [  0  50 205]
  ..

### 3. Video – acquisition and simple processing

In [ ]:
# Define a VideoCapture Object
cap = cv2.VideoCapture(0)
if not cap.isOpened():
    print("Cannot open camera")
    exit()

frame_nr = 0
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    
    # If frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break

    # Display the resulting frame
    cv2.imshow('webcam', frame)

    # Wait for user to press s to save frame
    if cv2.waitKey(1) == ord('s'):
        frame_name = 'frame' + str(frame_nr) + '.png'
        cv2.imwrite(frame_name, frame)
        cv2.imshow("Saved frame: " + frame_name, frame)
        cv2.waitKey(0)
        cv2.destroyWindow("Saved frame: " + frame_name)

    # Wait for user to press q to quit
    if cv2.waitKey(1) == ord('q'):
        break

    frame_nr += 1

# When everything is done, release the capture
cap.release()
cv2.destroyAllWindows()

Exercise 3.1 - Using the previous example as the baseline, implement a script that acquires the video from the webcam, converts it to grayscale, and shows the frames in binary format (i.e. the intensity of each pixel is 0 or 255); use a threshold value of 128.

In [ ]:
# Define a VideoCapture Object
cap = cv2.VideoCapture(0)
if not cap.isOpened():
    print("Cannot open camera")
    exit()

frame_nr = 0
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    
    # If frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break

    grayscale_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    _, threshhold_frame = cv2.threshold(grayscale_frame, 128, 255, cv2.THRESH_BINARY)

    # Display the resulting frame
    cv2.imshow('webcam', threshhold_frame)

    # Wait for user to press s to save frame
    if cv2.waitKey(1) == ord('s'):
        frame_name = 'frame' + str(frame_nr) + '.png'
        cv2.imwrite(frame_name, frame)
        cv2.imshow("Saved frame: " + frame_name, frame)
        cv2.waitKey(0)
        cv2.destroyWindow("Saved frame: " + frame_name)

    # Wait for user to press q to quit
    if cv2.waitKey(1) == ord('q'):
        break

    frame_nr += 1

# When everything is done, release the capture
cap.release()
cv2.destroyAllWindows()

Exercise 3.2 - Implement a simple detection/tracking algorithm for colored objects, using the following steps:
1) take each frame of the video;
2) convert from BGR to HSV color-space;
3) threshold the HSV image for a range of color values (creating a binary image);
4) extract the objects of the selected range (with a bitwise AND operation, using as operands the original and the binary image).

In [ ]:
# Define a VideoCapture Object
cap = cv2.VideoCapture(0)
if not cap.isOpened():
    print("Cannot open camera")
    exit()

frame_nr = 0
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    
    # If frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break

    hsv_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    _, threshhold_frame = cv2.threshold(hsv_frame, 128, 255, cv2.THRESH_BINARY)

    # Display the resulting frame
    cv2.imshow('webcam', threshhold_frame)

    # Wait for user to press s to save frame
    if cv2.waitKey(1) == ord('s'):
        frame_name = 'frame' + str(frame_nr) + '.png'
        cv2.imwrite(frame_name, frame)
        cv2.imshow("Saved frame: " + frame_name, frame)
        cv2.waitKey(0)
        cv2.destroyWindow("Saved frame: " + frame_name)

    # Wait for user to press q to quit
    if cv2.waitKey(1) == ord('q'):
        break

    frame_nr += 1

# When everything is done, release the capture
cap.release()
cv2.destroyAllWindows()